import { Inter } from 'next/font/google'
import '@styles/globals.css'
import { GoogleFonts } from 'next-google-fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'StalkYourStock',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <>
      <GoogleFonts href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" />

      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  )
}
